### ISSUE TITLE
[Feature Request] access_policies variable

### ISSUE THREAD

**Issue by angelbarrera92** [egarbi/terraform-aws-es-cluster#5]
Morning. Good morning. 

First of all, thank you very much for launching this project. 
The module is quite complete, but the `access_policies' configuration key is missing.

If it's okay with you, I do the development in my fork and pull you up a pull request.

I'm thinking of inserting: 
1. Optional variable with access policy. Default value `""`.
2. Insert this variable in the corresponding attribute of the `aws_elasticsearch_domain` resource.
3. Change the `README.md`.

Thanks in advance!

**Comment by egarbi** [comment]
@angelbarrera92 its done, try and let me know

**Comment by angelbarrera92** [comment]
Good morning @egarbi!
I tried the change and it's working fine. What's the next step? Make a tag in the git repository for "terraform registry" to take the new version?

Thanks!

**Comment by egarbi** [comment]
@angelbarrera92 I did it already. https://github.com/egarbi/terraform-aws-es-cluster/releases/tag/0.0.5 2 days ago.

**Comment by angelbarrera92** [comment]
Ouuuhhh Yeah. Thanks!
