### ISSUE TITLE
Resource not mentioned in access policy 

### ISSUE THREAD

**Issue by ranvijayj** [egarbi/terraform-aws-es-cluster#9]
Hi, 

In the readme 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "es:*",
            "Principal": "*",
            "Effect": "Allow",
            "Condition": {
                "IpAddress": {"aws:SourceIp": ["66.193.100.22/32"]}
            }
        }
    ]
}
```

The issue is how does one define "Resource" in the policy? Will it work without that?

**Comment by ranvijayj** [comment]
Also, In addition to the above point...

If I make a security group for ES and allow some IPs probably a "security group" in allow security group how do I mention that in the IpAddress field of the policy? Or Do I even need to do that?

```
resource "aws_security_group" "elasticsearch" {
  name        = "${var.name}"
  description = "Security Group to allow traffic to ElasticSearch"

NEEDED FOR PUBLIC IPS
#  ingress {
#    from_port   = 443
#    to_port     = 443
#    protocol    = "tcp"
#    cidr_blocks = ["${var.ingress_allow_cidr_blocks}"]
#  }

  ingress {
    from_port       = 443
    to_port         = 443
    protocol        = "tcp"
# SG can be changed
    security_groups = ["${aws_security_group.default.id}"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  vpc_id = "${module.vpc.vpc_id}"
}
```

I allowed default security group access to ES security group. Do I need to add anything in the condition for ES policy?

**Comment by egarbi** [comment]
@ranvijayj  the policy in the readme is just an example, you can use whatever you want there.
You can actually pass no policies at all. or use one allowing everything.
Also you only need to pass the policy, no need of a resource, `access_policy` is an attribute of elasticsearch resource.

Regarding the SG, Im not sure if I understand your question, note that the module creates already a SG for elasticsearch, if you want to allow access just set proper values for `ingress_allow_cidr_blocks` and/or `ingress_allow_security_groups`.
those CIDRS or SGs listed will be allowed to connect to the endpoint.
